services:
  - type: web
    name: healthcare-backend
    env: node
    plan: free
    region: oregon
  # Run npm inside the backend folder so Render finds backend/package.json
  buildCommand: "npm --prefix backend install"
  startCommand: "npm --prefix backend start"
    repo: "REPLACE_WITH_YOUR_GIT_REPO_URL"
    branch: main
    envVars:
      - key: MONGODB_URI
        value: ""
      - key: JWT_SECRET
        value: ""
      - key: CLOUDINARY_NAME
        value: ""
      - key: CLOUDINARY_API_KEY
        value: ""
      - key: CLOUDINARY_SECRET_KEY
        value: ""
      - key: RAZORPAY_KEY_ID
        value: ""
      - key: RAZORPAY_KEY_SECRET
        value: ""
      - key: STRIPE_SECRET_KEY
        value: ""
      - key: CURRENCY
        value: "INR"
